# Generated by Django 3.2.9 on 2021-11-22 22:15

import Aplus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to=Aplus.models.image_path),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_image',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to=Aplus.models.image_path),
        ),
    ]
