# Generated by Django 3.2.9 on 2021-11-23 22:50

import Aplus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplus', '0002_auto_20211123_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='user_grade',
            field=models.FileField(default=None, null=True, upload_to=Aplus.models.exclfile_path),
        ),
    ]
